### ISSUE TITLE
성 부분 벽돌섬이 콜리젼이 불안정함

### ISSUE THREAD

**Issue by sk7725** [sk7725/PrincessSavior#2]
기종: 에뮬레이터
버전: v0.2.0
재현: 성 부분 하늘섬 중 하나를 내려찍기 했는데 통과됨
해결책:
(임시) 플레이어 z축으로 확장 (localScale 1, 1, 2)
성 맵 수정

**Comment by Sharlottes** [comment]
https://user-images.githubusercontent.com/60801210/187128534-2a1c7b24-f7ae-45cc-aefc-9cdb9fbf670f.mp4

**Comment by sk7725** [comment]
아마 수정되었을 듯하지만 테스팅은 안됨

**Comment by sk7725** [comment]
0.4.2 기준 수정
