### ISSUE TITLE
검 부양 중 강화 다이얼로그를 누르면 캐릭터가 검을 내려침

### ISSUE THREAD

**Issue by Sharlottes** [sk7725/PrincessSavior#3]
기종 S9+, 버전 v0.2.0

https://user-images.githubusercontent.com/60801210/187076087-9de1e090-ab05-42df-806a-66ac3a8a1d78.mp4

비활성화 색이 되었음에도 불구하고 터치는 되어야...

**Comment by sk7725** [comment]
0.3.2 픽스
